use pesto_assignment;

-- Find the item that has minimum weight.
SELECT * FROM ITEMS WHERE WEIGHT IN (SELECT MIN(weight) FROM ITEMS);

-- Find the different warehouses in “Pune”
SELECT * FROM WAREHOUSES,CITIES WHERE CITIES.CITY_ID = WAREHOUSES.CITY_ID AND CITIES.CITY = 'PUNE';

-- Find the details of items ordered by a customer “HERMIONE GRANGER”
SELECT  C.CNAME AS 'CUSTOMER NAME' , O.ONO AS 'ORDER NUMBER', O.ODATE AS 'ORDER DATE', I.DESCRIPTION AS 'ITEM DESCRIPTION'
	FROM CUSTOMERS C, ORDERS O, ITEMS I 
	JOIN ITEMS_ORDERS 
	WHERE ITEMS_ORDERS.ONO = O.ONO AND O.CNO = C.CNO AND CNAME = 'HERMIONE GRANGER';
    
-- Find a Warehouse which has maximum stores.
SELECT * FROM WAREHOUSES 
	WHERE WID = (
		SELECT WID FROM STORES 
			GROUP BY WID 
			ORDER BY COUNT(*) 
			DESC LIMIT 1
    );

-- Find an item which is ordered for a minimum number of times.
SELECT * FROM ITEMS 
	WHERE ITEMNO = (
		SELECT ITEMNO FROM ITEMS_ORDERS 
			GROUP BY ITEMNO 
			ORDER BY COUNT(*) 
            LIMIT 1
	);
    
SELECT C.CNAME, I.DESCRIPTION, I.WEIGHT, I.COST, O.ODATE, C.CU_CITY FROM ORDERS O
	INNER JOIN CUSTOMERS C ON O.CNO = C.CNO
	INNER JOIN ITEMS_ORDERS IO ON IO.ONO = O.ONO
	INNER JOIN ITEMS I ON I.ITEMNO = IO.ITEMNO;