create database pesto_assignment;
use pesto_assignment;

-- Create Tables with appropriate Relations
CREATE TABLE CITIES(
    CITY_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CITY CHAR(20),
    STATE CHAR(20)
);

CREATE TABLE WAREHOUSES(
    WID INTEGER AUTO_INCREMENT PRIMARY KEY,
    WNAME CHAR(30),
    LOCATION CHAR(20),
    CITY_ID INTEGER,
    FOREIGN KEY (CITY_ID) REFERENCES CITIES(CITY_ID)
);

CREATE TABLE STORES(
    SID INTEGER AUTO_INCREMENT PRIMARY KEY,
    STORE_NAME CHAR(20),
    LOCATION_CITY CHAR(20),
    WID INTEGER,
    FOREIGN KEY (WID) REFERENCES WAREHOUSES(WID)
);

CREATE TABLE CUSTOMERS(
    CNO INTEGER AUTO_INCREMENT PRIMARY KEY,
    CNAME CHAR(20),
    ADDR VARCHAR(50),
    CU_CITY CHAR(20)
);

CREATE TABLE ORDERS(
    ONO INTEGER AUTO_INCREMENT PRIMARY KEY,
    ODATE DATE,
    CNO INTEGER,
    FOREIGN KEY (CNO) REFERENCES CUSTOMERS(CNO)
);

CREATE TABLE ITEMS(
    ITEMNO INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(50),
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(10,2)
);

-- ITEMS TO ORDERS TABLE

CREATE TABLE ITEMS_ORDERS(
    ITEM_ORDER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ORDERED_QUANTITY INTEGER,
    ITEMNO INTEGER,
    ONO INTEGER,
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO),
    FOREIGN KEY (ONO) REFERENCES ORDERS(ONO)
);
 
-- STORES TO ITEMS TABLE

CREATE TABLE STORES_ITEMS(
    STORE_ITEM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QUANTITY INTEGER,
    SID INTEGER,
    ITEMNO INTEGER,
    FOREIGN KEY (SID) REFERENCES STORES(SID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO)
);

INSERT INTO CITIES (CITY, STATE) VALUES ('LUCKNOW', 'UTTAR PRADESH');
INSERT INTO CITIES (CITY, STATE) VALUES ('JALANDHAR', 'PUNJAB');
INSERT INTO CITIES (CITY, STATE) VALUES ('PATNA', 'BIHAR');
INSERT INTO CITIES (CITY, STATE) VALUES ('GURGAON', 'HARYANA');
INSERT INTO CITIES (CITY, STATE) VALUES ('PUNE', 'MAHARASHTRA');
SELECT * FROM CITIES;

INSERT INTO WAREHOUSES (WNAME, LOCATION, CITY_ID) VALUES ('WAREHOUSE NO 1', 'ALIGANJ',  1); 
INSERT INTO WAREHOUSES (WNAME, LOCATION, CITY_ID) VALUES ('WAREHOUSE NO 2', 'MODEL TOWN',  2);
INSERT INTO WAREHOUSES (WNAME, LOCATION, CITY_ID) VALUES ('WAREHOUSE NO 3', 'GOMTI NAGAR',  1);
INSERT INTO WAREHOUSES (WNAME, LOCATION, CITY_ID) VALUES ('WAREHOUSE NO 4', 'HAYANTPUR',  4);
INSERT INTO WAREHOUSES (WNAME, LOCATION, CITY_ID) VALUES ('WAREHOUSE NO 5', 'MANESAR',  4);
INSERT INTO WAREHOUSES (WNAME, LOCATION, CITY_ID) VALUES ('WAREHOUSE NO 6', 'KORGAON',  5);
SELECT * FROM WAREHOUSES;

INSERT INTO STORES (STORE_NAME, LOCATION_CITY, WID) VALUES ('STORE NO 1', 'KANPUR', 1);
INSERT INTO STORES (STORE_NAME, LOCATION_CITY, WID) VALUES ('STORE NO 1', 'FARIDABAD', 3);
INSERT INTO STORES (STORE_NAME, LOCATION_CITY, WID) VALUES ('STORE NO 2', 'PHAGWARA', 2);
INSERT INTO STORES (STORE_NAME, LOCATION_CITY, WID) VALUES ('STORE NO 3', 'AGRA', 3);
INSERT INTO STORES (STORE_NAME, LOCATION_CITY, WID) VALUES ('STORE NO 1', 'PATAUDI', 5);
INSERT INTO STORES (STORE_NAME, LOCATION_CITY, WID) VALUES ('STORE NO 1', 'DHORKA', 4);
INSERT INTO STORES (STORE_NAME, LOCATION_CITY, WID) VALUES ('STORE NO 1', 'WADKI', 6);
SELECT * FROM STORES;

INSERT INTO CUSTOMERS(CNAME, ADDR, CU_CITY) VALUES('HARRY POTTER', 'PRESIDENTIAL HOUSE', 'DELHI');
INSERT INTO CUSTOMERS(CNAME, ADDR, CU_CITY) VALUES('RON WEASLEY', 'PRESIDENTIAL HOUSE', 'DELHI');
INSERT INTO CUSTOMERS(CNAME, ADDR, CU_CITY) VALUES('HERMIONE GRANGER', 'PRESIDENTIAL HOUSE', 'DELHI');
INSERT INTO CUSTOMERS(CNAME, ADDR, CU_CITY) VALUES('PERCY JACKSON', 'PRESIDENTIAL HOUSE', 'DELHI');
INSERT INTO CUSTOMERS(CNAME, ADDR, CU_CITY) VALUES('ANNABETH CHASE', 'PRESIDENTIAL HOUSE', 'DELHI');
SELECT * FROM CUSTOMERS;

INSERT INTO ORDERS(ODATE,CNO) VALUES('2023-01-30', 1);
INSERT INTO ORDERS(ODATE,CNO) VALUES('2023-02-04', 4);
INSERT INTO ORDERS(ODATE,CNO) VALUES('2023-02-03', 2);
INSERT INTO ORDERS(ODATE,CNO) VALUES('2023-02-02', 3);
INSERT INTO ORDERS(ODATE,CNO) VALUES('2023-02-01', 5);
SELECT * FROM ORDERS;

INSERT INTO ITEMS(DESCRIPTION, WEIGHT, COST) VALUES('WATCH', 0.10, 1000.00);
INSERT INTO ITEMS(DESCRIPTION, WEIGHT, COST) VALUES('MOBILE PHONE', 0.50, 2000.00);
INSERT INTO ITEMS(DESCRIPTION, WEIGHT, COST) VALUES('LAPTOP', 2.50, 10000.00);
INSERT INTO ITEMS(DESCRIPTION, WEIGHT, COST) VALUES('BAG', 0.60, 50.00);
SELECT * FROM ITEMS;

INSERT INTO ITEMS_ORDERS(ORDERED_QUANTITY, ONO, ITEMNO) VALUES(4, 1, 4);
INSERT INTO ITEMS_ORDERS(ORDERED_QUANTITY, ONO, ITEMNO) VALUES(1, 2, 1);
INSERT INTO ITEMS_ORDERS(ORDERED_QUANTITY, ONO, ITEMNO) VALUES(2, 2, 1);
INSERT INTO ITEMS_ORDERS(ORDERED_QUANTITY, ONO, ITEMNO) VALUES(5, 3, 2);
INSERT INTO ITEMS_ORDERS(ORDERED_QUANTITY, ONO, ITEMNO) VALUES(10, 4, 4);
INSERT INTO ITEMS_ORDERS(ORDERED_QUANTITY, ONO, ITEMNO) VALUES(2, 4, 3);

INSERT INTO STORES_ITEMS(QUANTITY, SID, ITEMNO) VALUES(30, 1, 1);
INSERT INTO STORES_ITEMS(QUANTITY, SID, ITEMNO) VALUES(40, 2, 2);
INSERT INTO STORES_ITEMS(QUANTITY, SID, ITEMNO) VALUES(20, 3, 3);
INSERT INTO STORES_ITEMS(QUANTITY, SID, ITEMNO) VALUES(100, 4, 4);